name: Publish package to GitHub Packages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      MAVEN_USERNAME: "runner"
      MAVEN_PASSWORD: ${{ secrets.TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install dependencies and build
        run: ./gradlew build --stacktrace

      - name: Run tests
        run: ./gradlew test --stacktrace

      - name: Publish package
        run: ./gradlew publish --stacktrace
